// Code generated by cmd/lexgenlite (see Makefile's lexgen); DO NOT EDIT.

package statusphere

// schema: xyz.statusphere.status

import (
	"github.com/agentio/atiquette/pkg/lexutil"
)

func init() {
	lexutil.RegisterType("xyz.statusphere.status", &Status{})
}

// RECORDTYPE: Status
type Status struct {
	LexiconTypeID string `json:"$type,const=xyz.statusphere.status" cborgen:"$type,const=xyz.statusphere.status"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	Status        string `json:"status" cborgen:"status"`
}
